### ISSUE TITLE
[Suggestion] Add caca.

### ISSUE THREAD

**Issue by Pankine** [Progressbar-Discord-Server/Processes#1]
title

**Comment by RealMCoded** [comment]
Approved

**Comment by 5jiji** [comment]
The sticker in the server has since been deleted, so why doing this joke?

**Comment by dewsmith0** [comment]
No it hasn't

**Comment by 5jiji** [comment]
Fuck
I thought it did

**Comment by zai-tm** [comment]
Add caca.

**Comment by RealMCoded** [comment]
Add caca.

**Comment by Pankine** [comment]
> The sticker in the server has since been deleted, so why doing this joke?

:nerd:

**Comment by nokteholda** [comment]
imagine caca issue
