### ISSUE TITLE
member count shows as NaN

### ISSUE THREAD

**Issue by RealMCoded** [Progressbar-Discord-Server/Processes#2]
![image](https://user-images.githubusercontent.com/34777184/214466711-4e98297e-d69a-472e-a700-4140542685ef.png)

**Comment by RealMCoded** [comment]
ok

**Comment by RealMCoded** [comment]
fix

**Comment by Pankine** [comment]
5jiji: no

**Comment by 5jiji** [comment]
Guess it fixed itself....

![image](https://github.com/user-attachments/assets/54ed54f4-c286-42e4-b297-79b28109ef69)
